### ISSUE TITLE
Incorporate last lesson's feedback to clean files

### ISSUE THREAD

**Issue by Erwin9411** [Erwin9411/projectDPREP2#6]
Incorporate the feedback form the last DPREP lesson.

Combine multiple tasks into 1, e.g. to replace strange characters with "".
Use  c(   to combine or create a function()

variablename <- dataframe %>% grepl(c(........

**Comment by bas-dekkers** [comment]
I have added a function which removes the last characters for all the columns in which this is necessary

**Comment by bas-dekkers** [comment]
I have just spend a significant amount of time writing a function with a for loop to change the brand names more easily than how we do now by replacing them one by one. I did in my opinion, exactly the same as Hannes was doing in the lesson last Friday, I started creating a list with the objects I want to change, begin a function, loop through those list of 2 items, said that I want to replace it by in this case "nokia" and ended with the variable "ret" as he created in the lesson. Then I did return(ret) but whatever I was trying to type next nothing changes or all the brands change to "nokia".

**Comment by bas-dekkers** [comment]
I thought maybe the issue was with the function so I now only tried it as a for loop, but if I loop the self-created list through the for loop it only recognizes the second input. So I thought maybe is it a good idea to change it into a data frame. However, this wasn't the solution because right now when I am running the for loop it deletes my whole brand column. I am out of ideas.

**Comment by bas-dekkers** [comment]
In Dutch we say "de aanhouder wint" because after trying once again I succeed in creating a function with a for loop to change brand names for the amazon data. I will upload this any second

**Comment by bas-dekkers** [comment]
I have also added a function which helps to get rid of some inconvenient observations in the star_rating column of the amazon dataset

**Comment by bas-dekkers** [comment]
Erwin is briefed about the progress made with this issue, he agrees that everything is done well.

**Comment by Erwin9411** [comment]
Looking good Bas! I like what you did with the mergin of the data set. I'll reshuffle the columns to make it a bit more comprehensive.

**Comment by Erwin9411** [comment]
Done. Order now is site, title, brand, price, ... ... ... , EAN, asin, date
